image:
  name: node:latest

# Extends
.deploy_to_dev:
  environment:
    context: dev
  filters:
    branches:
      only:
        - /feature\/.*/
        - /bugfix\/.*/

.deploy_to_stage:
  environment:
    context: stage
  filters:
    tags:
      only: /v.*/
    branches:
      ignore: /.*/

.deploy_to_production:
  environment:
    context: production
  filters:
    tags:
      only: /v.*/
    branches:
      ignore: /.*/

.install_dependencies: 
  script: 
    - echo 'install_dependencies'
    - yarn --no-progress --frozen-lockfile

stages:
  - flow
  - tests
  - build
  - bundle_analyzer
  - storybook
  - deploy
  - e2e

# Jobs
flow:
  stage: flow
  script:
    - echo 'check flow'

flow:coverage:
  stage: flow
  script:
    - echo 'flow coverage 100%'

storybook:
  stage: storybook
  script: 
    - echo 'Build storybook'

bundle_analyzer:
  stage: bundle_analyzer
  script: 
    - echo 'Bundle analyzer'

build:master:
  extends: .install_dependencies
  stage: build
  only:
    refs:
      - master
  after_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global push.default simple
    - git config --global user.email "gitlab@example.com"
    - git config --global user.name "Gitlab"
    - git checkout master
    - export CURRENT_HASH=$(echo $(git rev-parse --short HEAD))
    - echo $CURRENT_HASH
    - export COMMIT_MESSAGE="$(echo $(git log -n 1 --pretty=format:%B))"
    - echo $COMMIT_MESSAGE
    - export VERSION_TYPE="patch"
    - export TAG=$(echo $(git tag --contains $CURRENT_HASH))
    - echo $TAG
    #- export VERSION_TYPE=$(node pipelines/get-version-type.js "$COMMIT_MESSAGE")
    - if [ ! -z "$TAG" ] ; then exit 0; fi
    - echo $VERSION_TYPE
    - git --version
    - git status
    - npm version $VERSION_TYPE -m "v%s"
    - git status
    - git push --follow-tags

build:branch:
  extends: .install_dependencies
  stage: build
  only:
    - /^feature/.*$/

build:test-2:
  extends: .install_dependencies
  stage: build
  when: manual

deploy:stage:
  stage: deploy
  only:
    refs:
      - master
  script: 
    - echo 'Deploy to stage'

deploy:branch:
  stage: deploy
  only:
    - /^feature/.*$/
  script: 
    - echo 'Deploy to stage'

deploy:test-2:
  stage: deploy
  needs: ["build:test-2"]
  script: 
    - echo 'Deploy to test-2'
  
e2e:
  stage: e2e
  only:
    refs:
      - master
  script: 
    - echo 'Bundle analyzer'
    - echo Simulation e2e testing
    - npm run test:ci
  artifacts:
    paths: 
      - coverage
    name: coverage

tests:unit:
  extends: 
    - .install_dependencies
  stage: tests
  after_script: 
    - echo 'Bundle analyzer'
    - echo Simulation e2e testing
    - npm run test:ci
  cache:
    paths: 
      - node_modules 
  artifacts:
    paths: 
      - coverage
    name: coverage